### ISSUE TITLE
Update in plantuml-stdlib, request to tag version

### ISSUE THREAD

**Issue by Potherca** [Roemer/plantuml-office#5]
Hi! I'm in the process of opening MRs to update `*.puml` files in `plantuml-stdlib`, but since there is no versioning available in this repo, it's not something I can easily automate.

Would it be possible to add git tags to this project?

**Comment by Roemer** [comment]
Hi
Great! I just created an 1.0.0 tag so you can use that.

**Comment by Potherca** [comment]
Awesome, thanks!
