### ISSUE TITLE
Correct syntax for using router icon

### ISSUE THREAD

**Issue by tooh** [Roemer/plantuml-office#6]
What is the correct usage

This raises error

`OFF_ROUTER(router,Router)`

```
!include <tupadr3/common>

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/firewall_orange>
!include <office/Clouds/cloud_disaster_red>
!include <office/Devices/router>

title Office Icons Example

package "Sprites" {
        OFF_DATABASE_SERVER(db,DB)
        OFF_APPLICATION_SERVER(app,App-Server)
        OFF_FIREWALL_ORANGE(fw,Firewall)
        OFF_CLOUD_DISASTER_RED(cloud,Cloud)
        OFF_ROUTER(router,Router)
        db <-> app
        app <--> fw
        fw <.left.> cloud
}
```

**Comment by Roemer** [comment]
What version of PlantUML are you using?
Your example works on the latest version / online server:
http://www.plantuml.com/plantuml/uml/TT112zem50VmUpz5vgc3QW-xIY7QT1IAbLItOuZ9guJ59YIf7OnzzzNgb8BcyiB__U3ntXVL2TrBGElGMoxTjrIOoyLqMHIzMgPjbO2q0NS5vrF90pzn3ynFGVPPSckr4Zmeqtt6MzC9iC6dhN8mSAsPSRmxmpkgJIzzAcw5IUMv3-2O0_d6vd0TYq-TwSDjRXHKq83ggOjAOJgFo6z-iHgYo7BnYvy1BHhhL02_G7yYz7XrKR0S7_06DuGrXFuWD9Qd9DzydH6ytrVb5X_AUlTVSMiJREtoVeuvBqfAVkAgOZN5k-yaReUaUEm_XzkgFkOiBnlS70XbbEJnj7yo7MDkQNqSJNnVEQ5JUGbvGkjbXhYrpsZyZzaOjiCpQmUqNcbemof3qwJexpy0

**Comment by tooh** [comment]
Thanks for quick reply.

I use the Confluence plugin.

Probably this version is behind.
Will check and ask maintainer for update.

**Comment by tooh** [comment]
Plugin version we use is v6.34. This uses library version v1.2019.11.

But this does not explain it. IMHO

**Comment by Roemer** [comment]
Can you create a ticket at the maintainers site and post the link to the ticket here? As it works with the standalone PlantUML, it seems that there is an issue in the Confluence Plugin.

**Comment by Roemer** [comment]
Which Confluence plugin are you using?
I just tried with https://avono-support.atlassian.net/wiki/spaces/PUML/pages/9699367/Macro+plantuml and it seems to work.

**Comment by tooh** [comment]
https://avono-support.atlassian.net/browse/PUML-489

**Comment by tooh** [comment]
Issue can be closed. Error was due to version management of the diagram code.
The code in this issue works OK. The code on my confluence page had a small difference. @Roemer 

Thanks for assistance.
